//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictCOVID.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PREDICT_COVIDEntities : DbContext
    {
        public PREDICT_COVIDEntities()
            : base("name=PREDICT_COVIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANALYZED_PREDICTION> ANALYZED_PREDICTION { get; set; }
        public DbSet<Person> PEOPLE { get; set; }
        public DbSet<PREDICTION> PREDICTIONs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
