//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictCOVIDFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ANALYZED_PREDICTION = new HashSet<ANALYZED_PREDICTION>();
            this.PREDICTIONs = new HashSet<PREDICTION>();
            this.PREDICTIONs1 = new HashSet<PREDICTION>();
        }
    
        public string NAME { get; set; }
        public string PHOTO { get; set; }
    
        public virtual ICollection<ANALYZED_PREDICTION> ANALYZED_PREDICTION { get; set; }
        public virtual ICollection<PREDICTION> PREDICTIONs { get; set; }
        public virtual ICollection<PREDICTION> PREDICTIONs1 { get; set; }
    }
}
